[package]
name = "cosmos_proposals"
version = "0.0.0"
edition = "2021"

[profile.release]
lto = true
opt-level = "z"
strip = "debuginfo"

[lib]
crate-type = ["cdylib"]

[dependencies]
substreams = "0.5"
substreams-entity-change = { git = "https://github.com/streamingfast/substreams-sink-entity-changes", branch = "develop", package = "substreams-entity-change" }
substreams-cosmos = "0.1"
sha2 = "0.10.8"
prost = "0.11"
prost-types = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
