// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PartialTx {
    #[prost(message, optional, tag = "1")]
    pub body: ::core::option::Option<PartialTxBody>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PartialTxBody {
    #[prost(message, repeated, tag = "1")]
    pub messages: ::prost::alloc::vec::Vec<::prost_types::Any>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message, serde::Serialize, serde::Deserialize)]
pub struct Events {
    #[prost(message, repeated, tag = "1")]
    pub gov_params_changes: ::prost::alloc::vec::Vec<GovParamsChanges>,
    #[prost(string, repeated, tag = "2")]
    pub passed_proposal_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message, serde::Serialize, serde::Deserialize)]
pub struct GovParamsChanges {
    #[prost(string, tag = "1")]
    pub proposal_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub params: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message, serde::Serialize, serde::Deserialize)]
pub struct GovParamsOptional {
    #[prost(message, optional, tag = "1")]
    pub votingparams: ::core::option::Option<VotingParamsOptional>,
    #[prost(message, optional, tag = "2")]
    pub tallyparams: ::core::option::Option<TallyParamsOptional>,
    #[prost(message, optional, tag = "3")]
    pub depositparams: ::core::option::Option<DepositParamsOptional>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message, serde::Serialize, serde::Deserialize)]
pub struct VotingParamsOptional {
    #[prost(string, optional, tag = "1")]
    pub voting_period: ::core::option::Option<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message, serde::Serialize, serde::Deserialize)]
pub struct TallyParamsOptional {
    #[prost(string, optional, tag = "1")]
    pub quorum: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub threshold: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub veto_threshold: ::core::option::Option<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message, serde::Serialize, serde::Deserialize)]
pub struct DepositParamsOptional {
    #[prost(message, repeated, tag = "1")]
    pub min_deposit: ::prost::alloc::vec::Vec<Deposit>,
    #[prost(string, optional, tag = "2")]
    pub max_deposit_period: ::core::option::Option<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message, serde::Serialize, serde::Deserialize)]
pub struct Deposit {
    #[prost(string, tag = "1")]
    pub denom: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub amount: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
